# Generated by Django 3.0.7 on 2020-09-18 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'artist',
                'verbose_name_plural': 'artists',
            },
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
            },
        ),
        migrations.CreateModel(
            name='track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('openForRemix', models.BooleanField()),
                ('bpm', models.IntegerField()),
                ('creatorId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mixupAPI.artist')),
                ('genre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mixupAPI.genre')),
            ],
            options={
                'verbose_name': 'track',
                'verbose_name_plural': 'tracks',
            },
        ),
        migrations.CreateModel(
            name='track_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=75)),
                ('url', models.CharField(max_length=150)),
                ('dateUploaded', models.DateField(auto_now_add=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mixupAPI.artist')),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mixupAPI.track')),
            ],
            options={
                'verbose_name': 'track file',
                'verbose_name_plural': 'track files',
            },
        ),
        migrations.CreateModel(
            name='collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mixupAPI.artist')),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mixupAPI.track')),
            ],
            options={
                'verbose_name': 'collaborator',
                'verbose_name_plural': 'collaborators',
            },
        ),
    ]
