# Generated by Django 2.2.13 on 2020-09-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mixupAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track_file',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mixupAPI.Track'),
        ),
    ]
