# Generated by Django 3.0.7 on 2020-09-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixupAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
