# Generated by Django 2.2.13 on 2020-09-22 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mixupAPI', '0002_auto_20200922_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='creatorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mixupAPI.Artist'),
        ),
    ]
