# Generated by Django 3.0.7 on 2020-09-18 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mixupAPI', '0002_track_track_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mixupAPI.Artist'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='track',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mixupAPI.Track'),
        ),
        migrations.AlterField(
            model_name='track',
            name='creatorId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mixupAPI.Artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mixupAPI.Genre'),
        ),
        migrations.AlterField(
            model_name='track_file',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mixupAPI.Artist'),
        ),
        migrations.AlterField(
            model_name='track_file',
            name='track',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mixupAPI.Track'),
        ),
    ]
