# Generated by Django 2.2.13 on 2020-09-23 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mixupAPI', '0004_auto_20200922_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mixupAPI.Artist'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mixupAPI.Track'),
        ),
    ]
